#!/bin/bash

echo "🚀 Setting up EAS Build for BrewMaestro"
echo "======================================"
echo ""
echo "📋 You need to run this command from your terminal:"
echo ""
echo "eas project:init"
echo ""
echo "When prompted, answer 'y' to create a project for @sebadp/brew-maestro"
echo ""
echo "This will:"
echo "✅ Create a new project in your Expo account"
echo "✅ Generate a valid UUID and add it to app.json"
echo "✅ Enable EAS Build for this project"
echo ""
echo "After that, you can run:"
echo "eas build --platform android --profile preview"
echo ""
echo "🔑 This is a one-time setup. After this, builds will work automatically."