export const BEER_STYLES = [
  'American IPA',
  'New England IPA',
  'Double IPA',
  'American Pale Ale',
  'Amber Ale',
  'Brown Ale',
  'Blonde Ale',
  'Cream Ale',
  'Kolsch',
  'American Wheat',
  'Hefeweizen',
  'Belgian Witbier',
  'Pilsner',
  'German Helles Lager',
  'Vienna Lager',
  'Oktoberfest / Marzen',
  'American Lager',
  'Porter',
  'Robust Porter',
  'Stout',
  'Milk Stout',
  'Imperial Stout',
  'Irish Red Ale',
  'Scottish Ale',
  'Belgian Dubbel',
  'Belgian Tripel',
  'Saison / Farmhouse Ale',
  'Biere de Garde',
  'Sour / Berliner Weisse',
  'Gose',
  'Barrel-Aged Sour',
  'Barleywine',
] as const;

export type BeerStyle = typeof BEER_STYLES[number];
